### ISSUE TITLE
Share on Hugging Face

### ISSUE THREAD

**Issue by lhoestq** [epic-kitchens/epic-sounds-annotations#1]
Hi ! Congrats with the dataset :)

I was wondering if you considered sharing the dataset on Hugging Face ? Many audio datasets are already available there (e.g. for ASR), and this would allow anyone to be able to load the dataset in one line in python.

**Comment by dimadamen** [comment]
Thanks for your question. Due to GDPR compliance in storing our dataset, we can only keep it in GDPR-compliant servers. Do you know if such a server exists on Hugging Face? But for now we are only able to store our dataset at data.bris for these legal reasons.

**Comment by lhoestq** [comment]
As required by the european laws, the Hugging Face platform is GDPR compliant. This includes dataset hosting :)

**Comment by dimadamen** [comment]
Will ask the university legal team to look into this. Do you know where the material for such confirmation exists?

**Comment by lhoestq** [comment]
Awesome ! You can check our privacy policy: https://huggingface.co/privacy
Let me know if your team needs anything else

**Comment by ylacombe** [comment]
Hey @dimadamen, I wonder if you had any updates on this! This definitely could be a great addition to the Hugging Face platform and would greatly promote this dataset usage!
