### ISSUE TITLE
reproduce SLOWFAST_EPIC_SOUNDS.pyth results again

### ISSUE THREAD

**Issue by Acie7J** [epic-kitchens/epic-sounds-annotations#13]
The test file generated by this command has an online result of only 52.31. Moreover, after local verification, the SLOWFAST_EPIC_SOUNDS.pyth model and the model we trained ourselves use the same script, but one result is 53.73 and the other is 52.30. The difference is large and it is definitely not due to TTA.

**Comment by dimadamen** [comment]
You might be starting from a bad seed. Did you consider re-training?
Just to understand, our released model produces the results, it's your trained model that doesn't? This can be an outcome of data loading or bad seed.

**Comment by Acie7J** [comment]
Could you please explain what you mean by ‘seed’ in this context?

**Comment by Acie7J** [comment]
Could you please give me some examples of what the seed could be in this context?

**Comment by JacobChalk** [comment]
Libraries that involve randomness typically have 'seeds' which affects the outcome of the random outputs. Normally, this is randomly generated, but we have set a fixed seed of 0 for PyTorch and numpy in our code to try and alleviate this. However, this is not fool proof and can still result in poor training runs/variances (for example, we did not set the `PYTHONHASHSEED` environment variable, which may also have an impact). 

GPU hardware can also affect performance, we used eight Tesla V100 GPUs to train and evaluate our models, variances from this can affect results, particularly when multiple GPUs are involved. You may need to test a different seed for you own setup.

Note that perfect replication from training yourself will be very difficult to achieve as you are trying to get close to our exact weights. So some margin of error, either above or below our results, needs to be accepted. Our provided weights on this GitHub should still replicate our results.

**Comment by Acie7J** [comment]
Thank you
