### ISSUE TITLE
Inquiry about technical report and certificate for EPIC-SOUNDS Audio-Based Interaction Recognition Challenge at CVPR

### ISSUE THREAD

**Issue by Acie7J** [epic-kitchens/epic-sounds-annotations#14]
Hello,

I participated in the EPIC-SOUNDS Audio-Based Interaction Recognition Challenge at CVPR and placed third. It has been some time since the competition ended, but I have not yet received an email from the organizers requesting that I write a technical report. I would like to inquire if I have the opportunity to write a technical report and receive a certificate for my achievement.

Thank you for your time and assistance.

Best regards,
Yuqi Li

**Comment by JacobChalk** [comment]
Hi,

The email should have just been sent out directing you to the appropriate link to submit your report. This will be a Codalab "message to all" email with the subject heading "REMINDER: EPIC-SOUNDS Audio-Based Interaction Recognition Challenge - Technical Report" 

Thank you for taking part and we look forward to reading your methods! :)
