### ISSUE TITLE
Sound Event Detection Baseline?

### ISSUE THREAD

**Issue by astrocyted** [epic-kitchens/epic-sounds-annotations#16]
I was just wondering if you have a baseline for Sound event detection (prediction of onset/offsets) on this dataset to release ?

**Comment by dimadamen** [comment]
Not yet unfortunately.

**Comment by JacobChalk** [comment]
Hi, we have recently updated the EPIC challenges to now include an audio-based interaction detection challenge, along with an ActionFormer baseline! You can find more information at either this [GitHub Repo](https://github.com/epic-kitchens/C10-epic-sounds-detection), or at [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/17921)!
