### ISSUE TITLE
Inconsistency between annotation files and readme

### ISSUE THREAD

**Issue by savya08** [epic-kitchens/epic-sounds-annotations#2]
Hi. Kudos for this awesome work.

There seems to be an inconsistency between the annotation files and their description in the readme. The 'start_sample' and 'stop_sample' should be indices in the untrimmed audio according to the readme. In the CSV files, however, these fields seem to represent the start/end times of the audio annotation in seconds.

**Comment by JacobChalk** [comment]
Hi Savya, thank you for your comment! It appears this was an oversight, they should indeed match the description in the readme. We have now amended the start/stop sample for train and validation splits, thank you for pointing this out!
