### ISSUE TITLE
Issue with the data/annotations

### ISSUE THREAD

**Issue by savya08** [epic-kitchens/epic-sounds-annotations#3]
Hi. It seems to me that there is something off with either the sound waveform in the data or the start/stop sample in the annotations (particularly for the test split). For example, for narration_id `P02_106_2` the sound wave is of size (1544192,) while `start_sample=1705200` and `stop_sample=1777200`.

Here's how I'm accessing the sound clip for the i<sup>th</sup> annotation:
```
with h5py.File(data_path, "r") as f:
    waveform = f[video_id[i]][:]
waveform_segment = waveform[start_sample[i]:stop_sample[i]]
```
Am I missing something? TIA!

**Comment by JacobChalk** [comment]
Hi Savya, thank you for pointing out this issue! It appears the test timestamps sample indices were wrong by a factor of 10, this has now been amended. Apologies for any inconvenience and thanks again!
