### ISSUE TITLE
 No module named 'exp.nb_SparseImageWarp

### ISSUE THREAD

**Issue by haoshuai714** [epic-kitchens/epic-sounds-annotations#4]
i try run this code, but i have a bug, such as :
 File "/data/EPIC/epic_sounds/epic-sounds-annotations-main/src/slowfast/datasets/spec_augment.py", line 4, in <module>
    from exp.nb_SparseImageWarp import sparse_image_warp
ModuleNotFoundError: No module named 'exp.nb_SparseImageWarp'
could you give me some guid?

**Comment by JacobChalk** [comment]
Hi, this is related to the dependency [SpecAugment With PyTorch](https://github.com/zcaceres/spec_augment). The folder `exp` and hence `nb_SparseImageWarp` are here so you will have to install this somewhere using the instructions in the repo and the add it to your python path. Hope this helps!

**Comment by haoshuai714** [comment]
Thanks! i need to install [SpecAugment With PyTorch](https://github.com/zcaceres/spec_augment), then add it to my python path?
such as :export PYTHONPATH=/data/EPIC/audio_model/spec_augment-master:/data/EPIC/audio_model/slowfast:$PYTHONPATH
