### ISSUE TITLE
EPIC_audio.hdf5

### ISSUE THREAD

**Issue by haoshuai714** [epic-kitchens/epic-sounds-annotations#6]
Hi！Gould you give me EPIC_audio.hdf5 download link? Thanks!

**Comment by dimadamen** [comment]
Please send an email to uob-epic-kitchens@bristol.ac.uk. This cannot be made publicly.

**Comment by haoshuai714** [comment]
How big is this file? 7KB?

**Comment by dimadamen** [comment]
As I said, please send an email for any information about this file.
